### PR TITLE
Upgrade LibTorch to v1.10.1

### LINKED ISSUE #751: Upgrade LibTorch to v1.10.1
https://github.com/pytorch/pytorch/releases/tag/v1.10.1

Note that [LibTorch v1.10](https://github.com/pytorch/pytorch/releases/tag/v1.10.0) includes backwards incompatible changes.

### PR DESCRIPTION
**Pull request by hsbadr**
Closes #751 and #744.

- [X] Update LibTorch to version 1.10.1
- [X] Use CUDA 11.3 with LibTorch 1.10.1
- [X] Update GitHub Actions, including `lantern` builds
- [X] Re-generate `declarations.yaml` for LibTorch 1.10.1
- [x] Re-generate C++ code for LibTorch 1.10.1
- [ ] Update `lantern` for LibTorch 1.10.1
- [ ] Style and render documents
- [ ] Run unit tests
- [ ] Run reverse dependency checks
- [ ] Add NEWS bullet

@dfalbel I need your help on the `lantern` side.

### CODE REVIEW

**Comment by hsbadr** [comment]
@dfalbel `torchgen` doesn't handle `c10::string_view` or when `argument$dynamic_type`  is parsed as `::std::array<bool,N>`.

**Comment by dfalbel** [comment]
Thanks @hsbadr 
Yeah, sometimes this happens, we will need to add lantern and wrapper types to handle them. I can work on that soon!

**Comment by dfalbel** [comment]
@hsbadr I think most (if not all) of Rcpp/Lantern wrappers are working now. There are still a few tests failing though if you want to investigate.

**Comment by hsbadr** [comment]
> I think most (if not all) of Rcpp/Lantern wrappers are working now. There are still a few tests failing though if you want to investigate.

Sorry, I haven't been available to work on this.

**Comment by dfalbel** [comment]
No worries @hsbadr , thank you very much for getting this started!!

**Pull request merged**
