### PR TITLE
Add non abi build of LibLantern.

### LINKED ISSUE #530: non-abi version of libtorch
Curious if the non-abi version of libtorch is supported and if there's any easy way to get install_torch to download it e.g. from
https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.7.0%2Bcpu.zip 

I'm in a cluster environment and am getting /lib64/libm.so.6: version `GLIBC_2.23' not found See also:
https://github.com/pytorch/pytorch/issues/38765

Thanks!

### LINKED ISSUE #868: torch on aws lambda glibc 2.27 not found
I'm trying to make an AWS lambda Dockerfile that uses torch. We have it working for other R processes, but it fails to install libtorch, with this error:
```
#9 116.4 Error in cpp_lantern_init(file.path(install_path(), "lib")) :
#9 116.4   /opt/R/4.2.1/lib/R/library/torch/lib/liblantern.so - /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/R/4.2.1/lib/R/library/torch/lib/./libtorch_cpu.so)
#9 116.4 Calls: install_torch -> lantern_start -> cpp_lantern_init
#9 116.4 Execution halted
```

This is the Dockerfile:
```
FROM public.ecr.aws/lambda/provided
RUN yum -y install wget tar
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
  wget https://cdn.rstudio.com/r/centos-7/pkgs/R-4.2.1-1-1.x86_64.rpm && \
  yum -y install R-4.2.1-1-1.x86_64.rpm && \
  rm R-4.2.1-1-1.x86_64.rpm
ENV PATH="${PATH}:/opt/R/4.2.1/bin/"
RUN echo 'options(repos = c(CRAN = "https://cran.rstudio.com/"))' >> /opt/R/4.2.1/lib/R/etc/Rprofile.site
RUN Rscript -e "install.packages('torch')"
RUN Rscript -e "library(torch); install_torch()"
```

I think #530 is related (at least the most recent comment) but I don't understand what to do about it.

### PR DESCRIPTION
**Pull request by dfalbel**
FIX #530 
FIX #868 

Maybe related to #866

### CODE REVIEW

**Comment by jonthegeek** [comment]
This worked beautifully and closes #868!
What would it take to get this merged into main? Do you need any other testing or hardening to make sure it works?

**Comment by jonthegeek** [comment]
This also closes #530, I think.

**Comment by dfalbel** [comment]
Yes, I'll merge soon! I would like to add CI test that actually runs on a CentOS 7 container so we make sure it works in systems with older glibc installations.

**Comment by jonthegeek** [comment]
Perfect! Yeah, that makes sense!

**Pull request merged**
