### PR TITLE
Add batch_first arg for attention.

### PR DESCRIPTION
**Pull request by jonthegeek**
I haven't tested this; Rstudio crashed when I tried to build torch locally. Theoretically it's straightforward, but I'd definitely like to test it before I call this done. Any help is appreciated!

### CODE REVIEW

**Comment by dfalbel** [comment]
To build torch locally you will need to run `source('tools/buildlantern.R')`. THen `devtools::load_all()` should just work.

**Comment by jonthegeek** [comment]
I'm getting a bunch of errors like this: `c++.exe: error: C:/rtools42/permissive: No such file or directory`

Evidently some make vars are getting misinterpreted.

It may be time for me to finally learn about this WSL thing to run Linux on a Windows machine...

**Comment by dfalbel** [comment]
Hmm, I haven't seen those errors. Might be a problem with Rtools? 
Or maybe you will need to install the visual studio c++ compiler . I'll review this PR tomorrow!

**Comment by jonthegeek** [comment]
I was able to install this branch with install_github, so it's specifically something about sourcing that makes rtools act up. I'll keep poking at it, but I can use this workaround to try to actually sort out tests tomorrow.

**Comment by dfalbel** [comment]
Fix #829

**Pull request merged**
