### PR TITLE
fix R-level fr-FR translation

### PR DESCRIPTION
**Pull request by cregouby**
After some exchange with Philippe Grosjean during the French Rencontre R 2024, 
I finally got the correct way to wrap R-level messages so that they get translated.

```{r}
> withr::with_language(lang = "fr",
+                      torch_scalar_tensor(torch_randn(8, 2, 7))
+ )
Error in `value_error()` at torch/R/creation-ops.R:380:5:
! les valeurs doivent être de longueur 1
Run `rlang::last_trace()` to see where the error occurred.
Called from: signal_abort(cnd, .file)
Browse[1]> 
> 
```

**Note**
Cpp-level translation is 
 - missing (no collection of the messages in po(t) files yet) 
 - not working as it requires wrapping all C/C++ level `"messages"` into `_("message")` but gettext does not get the one in `Rcpp::stop()`. I'll make it explicit in a issue.

### CODE REVIEW

**Comment by dfalbel** [comment]
@cregouby I rebased the PR. Some test cases are failing, and they seem related to this PR.

**Comment by cregouby** [comment]
Oh ! Sorry for that. 
Please give me some time to have a deeper look...

**Comment by dfalbel** [comment]
No worries, let me know if you want me to take a look too!

**Comment by dfalbel** [comment]
I also just added you as a collaborator so you don't need to wait for me to approve and run your PR's.

**Comment by cregouby** [comment]
Thanks, I feel honored !

**Pull request merged**
