### PR TITLE
default to long

### PR DESCRIPTION
**Pull request by skeydan**

### CODE REVIEW

**Comment by dfalbel** [comment]
Two tests are failing with this change. I think it's the expectation that is wrong now. Do you mind fixing it?

**Comment by skeydan** [comment]
already on it :-) (((may have questions though)))

**Comment by skeydan** [comment]
I think that for
``` 
x <- 1:4
expect_equal_to_r(torch_tensor(x), x)
```

I need to add int64 stuff in lantern everywhere, analogous to this:

image

right?

**Comment by dfalbel** [comment]
I would just make something like:

```
expect_equal_to_r(torch_tensor(x)$to(dtype = torch_int()), x)
```

for now. Adding support for converting back from torch_long() is trickier to implement. See also 
#149

**Comment by skeydan** [comment]
done :-)
(hopefully i caught them all, because running `devtools::test()` locally segfaults for me...)

totally forgot about that issue #149...

**Comment by dfalbel** [comment]
Thanks! Working now :D

**Pull request merged**
