### PR TITLE
Distibutions docs

### PR DESCRIPTION
**Pull request by dfalbel**
Adding more docs

### CODE REVIEW

**Comment by dfalbel** [comment]
@krzjoa I added a small vignette showcasing distributions and tried to organise the docs. Would you take a look?

**Comment by krzjoa** [comment]
Ok, I'll check it in the next few days.

**Comment by dfalbel** [comment]
Thanks much! :)

**Comment by krzjoa** [comment]
I reviewed this PR and I think it looks good :sunglasses: 
We'll extend it successively when new distributions will be added.

**Comment by dfalbel** [comment]
Thanks @krzjoa , will proceed and merge this PR and start submitting a new version of torch to CRAN.

**Pull request merged**
