### PR TITLE
add vision_make_grid

### PR DESCRIPTION
**Pull request by skeydan**

### CODE REVIEW

**Comment by skeydan** [comment]
OK so running "document" definitely breaks it for me ... 

one problem i just noticed after pushing, so you can still see it in the original commit - https://github.com/mlverse/torch/pull/194/commits/d0dea2a41b146c7740aca2cd77a24e04269aeab5 - there's almost everything removed from NAMESPACE

the other one i noticed before, and that was the one why i couldn't start torch anymore yesterday ... but this i fixed by checking out `RcppExports.R` from gh ... this was the diff before i did that:

```
cpp_autograd_set_grad_mode <- function(enabled) {
-    invisible(.Call('_torch_cpp_autograd_set_grad_mode', PACKAGE = 'torchpkg', enabled))
+    invisible(.Call('_torch_cpp_autograd_set_grad_mode', PACKAGE = 'torch', enabled))
 }
 
 cpp_tensor_grad <- function(self) {
-    .Call('_torch_cpp_tensor_grad', PACKAGE = 'torchpkg', self)
+    .Call('_torch_cpp_tensor_grad', PACKAGE = 'torch', self)
 }
 
 cpp_tensor_set_grad_ <- function(self, new_grad) {
-    invisible(.Call('_torch_cpp_tensor_set_grad_', PACKAGE = 'torchpkg', self, new_grad))
+    invisible(.Call('_torch_cpp_tensor_set_grad_', PACKAGE = 'torch', self, new_grad))
 }
 
 cpp_tensor_requires_grad <- function(self) {
-    .Call('_torch_cpp_tensor_requires_grad', PACKAGE = 'torchpkg', self)
+    .Call('_torch_cpp_tensor_requires_grad', PACKAGE = 'torch', self)
 }
 
 cpp_torch_method_backward_self_Tensor <- function(self, gradient, keep_graph, create_graph) {
-    invisible(.Call('_torch_cpp_torch_method_backward_self_Tensor', PACKAGE = 'torchpkg', self, gradient, keep_graph, create_graph))
+    invisible(.Call('_torch_cpp_torch_method_backward_self_Tensor', PACKAGE = 'torch', self, gradient, keep_graph, create_graph))
 }
 
 cpp_autograd_backward <- function(tensors, grad_tensors, retain_graph, create_graph) {
-    invisible(.Call('_torch_cpp_autograd_backward', PACKAGE = 'torchpkg', tensors, grad_tensors, retain_graph, create_graph))
+    invisible(.Call('_torch_cpp_autograd_backward', PACKAGE = 'torch', tensors, grad_tensors, retain_graph, create_graph))
 }
 
 cpp_tensor_register_hook <- function(self, f) {
-    .Call('_torch_cpp_tensor_register_hook', PACKAGE = 'torchpkg', self, f)
+    .Call('_torch_cpp_tensor_register_hook', PACKAGE = 'torch', self, f)
 }
 
 cpp_tensor_remove_hook <- function(self, pos) {
-    invisible(.Call('_torch_cpp_tensor_remove_hook', PACKAGE = 'torchpkg', self, pos))
+    invisible(.Call('_torch_cpp_tensor_remove_hook', PACKAGE = 'torch', self, pos))
 }


```

Anyone knows what is going on? And i guess someone would have to run "document" for me, on this PR :-))

**Comment by dfalbel** [comment]
are you runnning `devtools::document()` or using the IDE shortcut?

**Comment by skeydan** [comment]
I was using the IDE... Now when I run `devtools::document()` directly instead, I get a segfault:

```
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/6797' in core file.
#0  0x00007f2b99c44f21 in laternLoadSymbol (pLib=0x562c86594340, name=..., ppSymbol=0x7f2b9932742c <lanternConfigure>, pError=0x7ffc26f982f0) at lantern/lantern.h:3931
3931	  *ppSymbol = NULL;

#0  0x00007f2b99c44f21 in laternLoadSymbol (pLib=0x562c86594340, name="lanternConfigure", ppSymbol=0x7f2b9932742c <lanternConfigure>, pError=0x7ffc26f982f0) at lantern/lantern.h:3931
#1  0x00007f2b99c450d9 in lanternInit (libPath="/home/key/code/mlverse/torch/inst/deps", pError=0x7ffc26f982f0) at lantern/lantern.h:3971
#2  0x00007f2b99d695f6 in cpp_lantern_init (path="/home/key/code/mlverse/torch/inst/deps") at lantern.cpp:27
#3  0x00007f2b99c007b5 in _torch_cpp_lantern_init (pathSEXP=0x562c85106bc0) at RcppExports.cpp:23129

```

**Comment by skeydan** [comment]
hehe found it :-)

```
lantern_h <- "~/RStudio/torch/lantern/include/lantern/lantern.h"
```
(wanted to submit separate PR but it just "got added" to this one ;-))

Now I was able to successfully document but there are changes to `lantern.h` which I thought I'd better not commit, e.g.

```
$ git diff lantern/include/lantern/lantern.h | grep lanternConfigure
-  LOAD_SYMBOL(lanternConfigure);
+  LOAD_SYMBOL(_lanternConfigure);

$ git diff lantern/include/lantern/lantern.h | grep lantern_Tensor_numel
-  LOAD_SYMBOL(_lantern_Tensor_numel);
+  LOAD_SYMBOL(__lantern_Tensor_numel);

```

**Comment by dfalbel** [comment]
Actually, I said the wrong name of the script :( It's https://github.com/mlverse/torch/blob/master/tools/renamelib.R .
The problem is that the IDE runs Rcp::compileAttributes when you run document, but doens't build and `renamelib` is only run when the build happens.

**Comment by skeydan** [comment]
that's good to know in any case!

**Pull request merged**
