### PR TITLE
Dummy PR to test styling

### PR DESCRIPTION
**Pull request by dfalbel**

### CODE REVIEW

**Comment by hsbadr** [comment]
Thanks for testing this! Can you also cancel the old GHA runs from #753?

**Comment by hsbadr** [comment]
@dfalbel We don't need this condition:
https://github.com/mlverse/torch/blob/55e25551e4b7c7491ee8e0c8fbb9128af52a4bcb/.github/workflows/pr-commands.yaml#L38

**Comment by hsbadr** [comment]
@dfalbel Do you know why GPU runs are stuck? Can you cancel all workflow runs, if it's a queue/limit issue? I think this started with https://github.com/mlverse/torch/actions/runs/1704351616, with win-gpu label on forked branch, which is still pending.

**Comment by hsbadr** [comment]
Is it related to the following error:
```c++
lantern/src/Contrib/SortVertices/sort_vert.h:30:1: error: ‘at’ does not name a type; did you mean ‘auto’?
 at::Tensor sort_vertices(at::Tensor vertices, at::Tensor mask,
 ^~
 auto
 ```

**Comment by hsbadr** [comment]
> Is it related to the following error:
> 
> ```c++
> lantern/src/Contrib/SortVertices/sort_vert.h:30:1: error: ‘at’ does not name a type; did you mean ‘auto’?
>  at::Tensor sort_vertices(at::Tensor vertices, at::Tensor mask,
>  ^~
>  auto
> ```

@dfalbel Could test moving `#include "sort_vert.h"` after `torch`/`lantern` headers?
https://github.com/mlverse/torch/blob/1c012d27c453da5d4b47d74dec1046614d87eda2/lantern/src/Contrib/SortVertices/sort_vert.cpp#L28-L34

**Comment by hsbadr** [comment]
@dfalbel Never mind! Fixed by #757.

**Comment by dfalbel** [comment]
The GPU server is probably off in my office. I'll turn it on tomorrow, but no need to worry about it.

**Comment by hsbadr** [comment]
> The GPU server is probably off in my office. I'll turn it on tomorrow, but no need to worry about it.

Sounds good. @dfalbel Could you also cancel the following GHA runs in case it's queued due to them?
- `Test #3413`: https://github.com/mlverse/torch/actions/runs/1704351616
- `Test #3414`: https://github.com/mlverse/torch/actions/runs/1704393667
- `Test #3415`: https://github.com/mlverse/torch/actions/runs/1704406087
- `Test #3416`: https://github.com/mlverse/torch/actions/runs/1704780262
- `Test #3421`: https://github.com/mlverse/torch/actions/runs/1704780262

**Comment by dfalbel** [comment]
No worries, they will run when I turn on the server or timeout after some time.

**Pull request closed without merging**
